### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by PrathameshKesarkar** [julianostarek/music#1]
First of all, your app looks amazing. I have quick question for you. Are you maintaining your own database for Music or using a content provider to get all the available music from the device. cause as far as I can tell the built-in Content Provider is absurd for maintaining songs by artist.

**Quick Suggestion**

Why not put the *.gradle files and google.json files in .gitignore rather than committing the dummy files.

**Comment by jlnstrk** [comment]
First, I'm using Android's ContentProvider.
Second, I'm having a seperate branch containing all files which I'm only pushing to my private repo; using dummies together with artificial merge conflicts allows me to keep those files indexed

**Comment by PrathameshKesarkar** [comment]
So you are using MediaRetriever for extracting the Meta-data from the song

**Comment by jlnstrk** [comment]
@PrathameshKesarkar no. As I've said, I'm using Android's ContentProvider framework to access the OS's built-in media database

**Comment by PrathameshKesarkar** [comment]
Ok Thankyou!! for answer the questions. can I add you on G+ if you don't mind
